# Generated by Django 5.1.14 on 2025-11-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('operacoes', '0001_initial'),
        ('produtos', '0001_initial'),
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='vendedores.vendedor'),
        ),
        migrations.AddField(
            model_name='remessa',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='remessa',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas', to='vendedores.vendedor'),
        ),
        migrations.AddField(
            model_name='remessaitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='remessaitem',
            name='remessa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='operacoes.remessa'),
        ),
    ]
