# Generated by Django 5.1.14 on 2025-11-21 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remessaitem',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
