# Generated by Django 5.1.14 on 2025-11-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_alter_remessaitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remessaitem',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
